# Uncomment the next line to define a global platform for your project
  platform :ios, '10.3'

target 'AuxiFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuxiFit
  pod 'Firebase/Core'

  target 'AuxiFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuxiFitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
